/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { Image } from "@boundaryml/baml"

import * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}


export interface AskUser {
    tool_name: "ask_followup_question"
    message?: (string | null)
}

export interface AttemptCompletion {
    tool_name: "attempt_compeletion"
    result?: (string | null)
    command?: (string | null)
}

export interface ListCodeDefinitionNames {
    tool_name: "list_code_definition_names"
    path?: (string | null)
}

export interface ListFiles {
    tool_name: "list_files"
    path?: (string | null)
    recursive?: (boolean | null)
}

export interface ProjectEnvironment {
    osName?: (string | null)
    cwd?: (string | null)
    cwdFileList?: (string | null)
}

export interface ReadFile {
    tool_name: "read_file"
    path?: (string | null)
}

export interface Request {
    request?: (string | null)
    file_list?: (string | null)[]
    environment_details?: partial_types.ProjectEnvironment | null
    previous_tool_results?: partial_types.ToolRequestResponse | null[]
}

export interface Resume {
    name?: (string | null)
    email?: (string | null)
    experience?: (string | null)[]
    skills?: (string | null)[]
}

export interface SearchAndReplace {
    tool_name: "search_and_replace"
    path?: (string | null)
    operations?: partial_types.SearchAndReplaceOperations | null[]
}

export interface SearchAndReplaceOperations {
    search?: (string | null)
    replace?: (string | null)
    start_line?: (number | null)
    end_line?: (number | null)
    use_regex?: (boolean | null)
    regex_flags?: (string | null)
    ignore_case?: (boolean | null)
}

export interface ToolRequest {
    reason?: (string | null)
    tool?: (partial_types.ListFiles | null | partial_types.ReadFile | null | partial_types.AskUser | null | partial_types.AttemptCompletion | null | partial_types.WriteToFile | null | partial_types.SearchAndReplace | null | null)
}

export interface ToolRequestResponse {
    tool_request?: partial_types.ToolRequest | null
    response?: (string | null)
}

export interface UserResponse {
    message_to_user?: (string | null)
}

export interface WriteToFile {
    tool_name: "write_to_file"
    path?: (string | null)
    content?: (string | null)
}
